name: Compile and Build Application for iOS

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest 
    steps:

      #1 Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      #2 Install Java using setup-java subaction
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: "17"
      
      #3 Install Flutter using subosito subaction
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.2"
          channel: 'stable'
      
      #4 Install flutter project dependencies
      - name: Get dependencies
        run: flutter pub get
      
      #5 Run Flutter Test
      # Status: disabled
      # Todo: Write the tests before uncommenting this
      # - name: Run flutter test
      #   run: flutter test

      #6 Build iOS Application Archive
      - name: Build IPA
        run:
          flutter build ipa --no-codesign
      - name: Compress Archives and IPAs
        run: |
          cd build
          tar -czf ios_build.tar.gz ios

      #7 Save build artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Releases
          path: |
            build/ios_build.tar.gz
      
      # Create an automatic release
      # Status: disabled, need GH_TOKEN
      # See:  https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      #
      # - name: Create Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/app/outputs/bundle/release/app-release.aab,build/ios_build.tar.gz"
      #     tag: v1.0.${{ github.run_number }}
      #     token: ${{ secrets.TOKEN }}